# Generated by Django 5.0.1 on 2025-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_add_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_link',
            field=models.URLField(default=True, help_text='Link to your resume (Google Drive, Dropbox, etc.)', max_length=500),
            preserve_default=False,
        ),
    ]
