# Generated by Django 5.0.1 on 2025-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pglisting',
            name='gender_preference',
            field=models.CharField(choices=[('Male', 'Male Only'), ('Female', 'Female Only'), ('Co-ed', 'Co-ed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='property_type',
            field=models.CharField(choices=[('Coliving', 'Coliving Space'), ('PG', 'PG'), ('Hostel', 'Hostel'), ('Apartment', 'Apartment'), ('Independent House', 'Independent House')], default='Coliving', max_length=20),
        ),
    ]
