# Generated by Django 5.0.2 on 2025-04-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg_rental', '0002_alter_pglisting_gender_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pglisting',
            name='amenities',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
