# Generated by Django 5.0.2 on 2025-04-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_rental', '0003_remove_pglisting_amenities_delete_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pglisting',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
