# Generated by Django 5.0.2 on 2025-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_rental', '0004_pglisting_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
