# Generated by Django 5.0.2 on 2025-04-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('rules', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='subreddit_banners/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subreddit_icons/')),
            ],
            options={
                'verbose_name': 'Subreddit',
                'verbose_name_plural': 'Subreddits',
                'ordering': ['-created_at'],
            },
        ),
    ]
