# Generated by Django 5.0.2 on 2025-04-05 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subreddits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_subreddits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_subreddits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_subreddits', to=settings.AUTH_USER_MODEL),
        ),
    ]
