# Generated by Django 5.0.1 on 2025-04-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_code',
        ),
    ]
