# Generated by Django 5.0.2 on 2025-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delhi_wiki', '0002_eventreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
