# Generated by Django 5.0.2 on 2025-04-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delhi_wiki', '0003_area_is_approved_alter_area_name_alter_area_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodplace',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landmark',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='market',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
