# Generated by Django 5.0.1 on 2025-04-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delhi_wiki', '0005_metroline_metrostation_metroroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='metroroute',
            name='time',
            field=models.IntegerField(default=True, help_text='Estimated journey time in minutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metroroute',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metroroute',
            name='fare',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metroroute',
            name='interchange_stations',
            field=models.ManyToManyField(blank=True, related_name='route_interchanges', to='delhi_wiki.metrostation'),
        ),
    ]
