# Generated by Django 5.0.1 on 2025-04-07 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=100, unique=True)),
                ('agency_name', models.CharField(max_length=200)),
                ('agency_url', models.URLField()),
                ('agency_timezone', models.CharField(max_length=100)),
                ('agency_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('agency_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FareAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_id', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_type', models.CharField(max_length=3)),
                ('payment_method', models.IntegerField()),
                ('transfers', models.IntegerField()),
                ('transfer_duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=100, unique=True)),
                ('route_short_name', models.CharField(max_length=50)),
                ('route_long_name', models.CharField(max_length=200)),
                ('route_desc', models.TextField(blank=True, null=True)),
                ('route_type', models.IntegerField(choices=[(0, 'Tram, Streetcar, Light rail'), (1, 'Subway, Metro'), (2, 'Rail'), (3, 'Bus'), (4, 'Ferry'), (5, 'Cable tram'), (6, 'Aerial lift'), (7, 'Funicular'), (11, 'Trolleybus'), (12, 'Monorail')])),
                ('route_url', models.URLField(blank=True, null=True)),
                ('route_color', models.CharField(blank=True, max_length=6, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=6, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_service.agency')),
            ],
        ),
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contains_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_service.fareattribute')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_service.route')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=100, unique=True)),
                ('stop_code', models.CharField(blank=True, max_length=50, null=True)),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_desc', models.TextField(blank=True, null=True)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('zone_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stop_url', models.URLField(blank=True, null=True)),
                ('location_type', models.IntegerField(default=0)),
                ('wheelchair_boarding', models.IntegerField(default=0)),
                ('parent_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_service.stop')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100)),
                ('trip_id', models.CharField(max_length=100, unique=True)),
                ('trip_headsign', models.CharField(blank=True, max_length=200, null=True)),
                ('trip_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('direction_id', models.IntegerField(choices=[(0, 'Outbound'), (1, 'Inbound')])),
                ('block_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wheelchair_accessible', models.IntegerField(default=0)),
                ('bikes_allowed', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_service.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_sequence', models.IntegerField()),
                ('stop_headsign', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_type', models.IntegerField(default=0)),
                ('drop_off_type', models.IntegerField(default=0)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
                ('timepoint', models.IntegerField(default=1)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_service.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_service.trip')),
            ],
            options={
                'ordering': ['trip', 'stop_sequence'],
            },
        ),
        migrations.CreateModel(
            name='UserFareHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journey_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('destination_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_fares', to='bus_service.stop')),
                ('origin_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_fares', to='bus_service.stop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_service.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
