# Generated by Django 5.0.1 on 2025-04-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['stop_name'], 'verbose_name': 'Bus Stop', 'verbose_name_plural': 'Bus Stops'},
        ),
    ]
